// import { fontawesome } from "./fontawesome";
// import { anime } from "./anime";
// import { fabric } from "./fabric";
import { ripple } from "./ripple";
import { doubletap } from "./doubletap";
import { script } from "./script";
// fontawesome();
// anime();
// fabric();
ripple();
doubletap();
script();